export default {
    "APP_NAME": "Money App",
    "EMAIL_USERNAME": "Email",
    "EMAIL": "Email",
    "FULL_NAME": "Full Name",
    "FULL_NAME_VALIDATION": "Please enter your full name.",
    "EMAIL_PLACEHOLDER": "Enter email address",
    "EMAIL_LOGIN_VALIDATION": "Please enter valid email address.",
    "EMAIL_VALIDATION": "Please enter valid email address.",
    "PHONE_NUMBER": "Contact Number",
    "PHONE_NUMBER_VALIDATION": "Please enter contact number.",
    "PHONE_PLACEHOLDER": "Enter contact number.",
    "PASSWORD": "Password",
    "CONFIRM_PASSWORD": "Confirm Password",
    "PASSWORD_VALIDATION": "Please enter password.",
    "PASSWORD_PLACEHOLDER": "Enter password",
    "CONFIRM_PASSWORD_PLACEHOLDER": "Enter confirm password",
    "CONFIRM_PASSWORD_VALIDATION": "Please enter confirm password.",
    "PASSWORD_NOT_MATCHED": "Password and Confirm Password must be same.",
    "LOGIN": "Login",
    "FORGOT_PASSWORD": "Forgot Password",
    "SIGNUP": "Sign Up",
    "SIGNUP_TEXT": "Don't have an account yet?",
    "CLICK_SIGNUP": "Click here to Signup",
    "FORGOT_INFO_TEXT": "Please, enter your email address. You will receive a new password via email.",
    "LOGIN_BUTTON": "LOGIN",
    "SIGNUP_BUTTON": "SIGN UP",
    "SEND": "SEND",
    "NEW_CATEGORY": "New Category",
    "EXAMPLE": "Example",
    "CATEGORY_EXAMPLE": "My Gift Money, Jim's Birthday, Summer Clothes, Eat Out, Sue's Allowance",
    "ADD_CATEGORY": "Add Category",
    "EDIT_CATEGORY": "Edit Category",
    "CATEGORY": "Category",
    "CATEGORY_PLACEHOLDER":"Enter Category",
    "LOGOUT": "Logout",
    "LOGOUT_CONFIRMATION": "Are you sure you want to logout?",
    "DELETE_ACCOUNT": "Delete Account",
    "DELETE_ACCOUNT_CONFIRMATION_HEADING": "Are you sure you want to delete your account?",
    "DELETE_ACCOUNT_CONFIRMATION_MESSAGE": "By deleting your account, all of your data will be permanently removed. This includes your profile information, categories, and other associated content. Once deleted, this information cannot be recovered.",
    "DELETE": "Yes, Delete",
    "CANCEL": "Cancel",
    "TERMS": "Terms & Conditions",
    "PRIVACY": "Privacy Policy",
    "CHANGE_PASSWORD": "Change Password",
    "ALL_TRANSACTIONS": "All Transctions",
    "NO_TRANSACTIONS_MESSAGE": "You have no transactions in this category.",
    "SUBMIT": "Submit",
    "CATEGORY_VALIDATION": "Please enter Category.",
    "API_ERROR_MESSAGE": "Something went wrong! Please try again later.",
    "ADD_CATEGORY_VALIDATION": "Please enter category.",
    "HI": "Hi",
    "DESCRIPTION": "Description",
    "AMOUNT": "Amount",
    "MINUS_DESCRIPTION": "What did you buy?",
    "ADD_MONEY": "Add Money",
    "SPEND_MONEY": "Spend Money",
    "DESCRIPTION_ERROR": "Please enter the description.",
    "AMOUNT_ERROR": "Please enter the amount.",
    "CURRENT_PASSWORD": "Current Password",
    "NEW_PASSWORD": "New Password",
    "CONFIRM_NEW_PASSWORD": "Confirm New Password",
    "CURRENT_PASSWORD_VALIDATION": "Please enter valid current password.",
    "NEW_PASSWORD_VALIDATION": "Please enter new password.",
    "CONFIRM_NEW_PASSWORD_VALIDATION": "Please enter confirm new password.",
    "NO_CATEGORY_MESSAGE": "You have no categories/transactions yet. Please add a new category.",
    "DELETE_CATEGORY": "Delete Category",
    "DELETE_CATEGORY_MESSAGE": "Are you sure?\n You want to delete this category.",
}
